variable "region" {}
variable "project" {}
variable "env" {}
variable "vpc_id" {}
variable "vpc_cidr" {}
variable "public_key" {}
variable "ecr_repository" {}
variable "ecs_role_arn" {}
variable "db_user_name" {}
variable "db_user_password" {}
variable "db_instance_class" {}
variable "rds_role_arn" {}
variable "my_domain" {}
variable "hosted_zone_id" {}
variable "acm_certificate_arn" {}
variable "rails_master_key" {}
variable "elb_bucket_name" {}
