Cloud.create(name: "AWS", vendor: "Amazon")
Cloud.create(name: "Azure", vendor: "Microsoft")
Cloud.create(name: "GCP", vendor: "Google")
Cloud.create(name: "Alibaba Cloud", vendor: "Alibaba")
Cloud.create(name: "IBM Cloud", vendor: "IBM")
